"""
This Veros setup file was generated by

   $ veros copy-setup acc_sector

on 2024-08-02 13:45:50 UTC.
"""

from veros import runtime_settings as rs

# Configure JAX and MPI settings
rs.backend = "jax"  # Use JAX for computations
rs.linear_solver = "best"

__VEROS_VERSION__ = '1.5.1'

if __name__ == "__main__":
    raise RuntimeError(
        "Veros setups cannot be executed directly. "
        f"Try `veros run {__file__}` instead."
    )

# -- end of auto-generated header, original file below --

from veros import VerosSetup, veros_routine

from veros.variables import allocate, Variable
from veros.distributed import global_min, global_max
from veros.core.operators import numpy as npx, update, at
import veros.tools
import h5netcdf # type: ignore

from scipy.interpolate import RegularGridInterpolator
from scipy.interpolate import CubicHermiteSpline
from scipy.interpolate import splrep, splev


class ACCSectorSetup(VerosSetup):
    """A model using spherical coordinates with a partially closed domain representing the narrow sector of Atlantic and ACC.

    The bathymetry of the model is idealized to a flat-bottom (with depth of 4000 m) over the majority of the domain,
    except a half depth appended within the confines of the circumpolar channel at the inflow and outflow regions.
    The horizontal grid has resolution of :math:`2 \\times 2` degrees, and the vertical one has 40 levels.

    Wind forcing over the sector part and buoyancy relaxation drive a large-scale meridional overturning circulation.

    This setup demonstrates:
     - setting up an idealized geometry after `(Munday et al., 2013) <https://doi.org/10.1175/JPO-D-12-095.1>`_.
     - sensitivity of circumpolar transport and meridional overturning
       to changes in Southern Ocean wind stress and buoyancy anomalies
     - basic usage of diagnostics

    :class:`Adapted from ACC channel model <veros.setups.acc.ACCSetup>` anf from Roman Nuterman code.

    Reference:

        Laurits S. Andreasen. (2019). Time scales of the Bipolar seesaw: The role of oceanic cross-hemisphere signals,
            Southern Ocean eddies and wind changes, MSc Thesis, 42p.
            `<https://sid.erda.dk/share_redirect/CVvcrowL22/Thesis/Laurits_Andreasen_MSc_thesis.pdf>`_.

    """

    max_depth = 4000.0 
    lat_min = -70.
    lat_max = 70.
    lon_min = 0.
    lon_max = 50.
    res = 1.0

    @veros_routine
    def set_parameter(self, state):

        settings = state.settings

        settings.identifier = "neverworld2"
        settings.description = "Neverworld 2 model"

        settings.nx = 52
        settings.ny = 140
        
        settings.nz = 36
        
        settings.dt_mom = 3600.0
        settings.dt_tracer = 3600.0
        settings.runlen = 86400 * 2

        settings.x_origin = 0.0
        settings.y_origin = -70.0

        settings.coord_degree = True
        settings.enable_cyclic_x = True

        settings.enable_neutral_diffusion = True
        settings.K_iso_0 = 1000.0
        settings.K_iso_steep = 500.0
        settings.iso_dslope = 0.005
        settings.iso_slopec = 0.01
        settings.enable_skew_diffusion = True

        settings.enable_hor_friction = True
        settings.A_h = 1e5
        settings.enable_hor_friction_cos_scaling = True
        settings.hor_friction_cosPower = 1

        settings.enable_bottom_friction = True
        settings.r_bot = 1e-5

        settings.enable_implicit_vert_friction = True

        settings.enable_tke = True
        settings.c_k = 0.1
        settings.c_eps = 0.7
        settings.alpha_tke = 30.0
        settings.mxl_min = 1e-8
        settings.tke_mxl_choice = 2
        settings.kappaM_min = 2e-4
        settings.kappaH_min = 2e-5
        settings.enable_Prandtl_tke = False  
        settings.enable_kappaH_profile = True

        settings.K_gm_0 = 1000.0
        settings.enable_eke = True  
        settings.eke_k_max = 1e4
        settings.eke_c_k = 0.4
        settings.eke_c_eps = 0.5
        settings.eke_cross = 2.0
        settings.eke_crhin = 1.0
        settings.eke_lmin = 100.0
        settings.enable_eke_superbee_advection = False  
        settings.enable_eke_isopycnal_diffusion = False

        settings.enable_idemix = False
        settings.enable_idemix_hor_diffusion = False  
        settings.enable_eke_diss_surfbot = False  
        settings.eke_diss_surfbot_frac = 0.2  
        settings.enable_idemix_superbee_advection = False  

        settings.eq_of_state_type = 3

        var_meta = state.var_meta
        var_meta.update(t_rest=Variable("t_rest", ("xt", "yt"), "1/s", "Surface temperature restoring time scale"),
                        s_rest=Variable("s_rest", ("xt", "yt"), "1/s", "Surface salinity restoring time scale"),
                        t_star=Variable("t_star", ("yt",), "deg C", "Reference surface temperature"),
                        s_star=Variable("s_star", ("yt",), "psu", "Reference surface salinity"),
                        )

        #     t_star=Variable("t_star", ("yt",), "deg C", "Reference surface temperature"),

    @veros_routine
    def set_grid(self, state):
        vs = state.variables
        settings = state.settings
        vs.dxt = update(vs.dxt, at[...], self.res * 52 / settings.nx)
        vs.dyt = update(vs.dyt, at[...], self.res * 140 / settings.ny)

        vs.dzt = veros.tools.get_vinokur_grid_steps(settings.nz, self.max_depth, 10.0, refine_towards="lower")

    @veros_routine
    def set_coriolis(self, state):
        vs = state.variables
        settings = state.settings
        vs.coriolis_t = update(
            vs.coriolis_t, at[:, :], 2 * settings.omega * npx.sin(vs.yt[None, :] / 180.0 * settings.pi)
        )

    @veros_routine
    def set_topography(self, state):
        vs = state.variables
        settings = state.settings

        lat_mesh_t, lon_mesh_t = npx.meshgrid(vs.yt, vs.xt)
        
        vs.bathymetry = npx.full(lon_mesh_t.shape, 0)
        vs.bathymetry = update(vs.bathymetry, at[...], self.get_bathymetry(self, state, lon_mesh_t, lat_mesh_t, H_min=0.))
        vs.bathymetry = update(vs.bathymetry, at[...], self.add_gauss_ring(self, state, lon_mesh_t, lat_mesh_t))

        ## Roman's version :
        # with h5netcdf.File("/home/x_titmo/work/setup/NeverWorld2/neverworld2_bathy.nc", "r") as topography_file:
        #     topo_x, topo_y, topo_z = (npx.array(topography_file.variables[k], dtype="float").T for k in ("x", "y", "bathy"))

        topo_z = -vs.bathymetry
        topo_z = npx.minimum(topo_z, 0.0)

        depth_levels = 1 + npx.argmin(npx.abs(topo_z[:, :, npx.newaxis] - vs.zt[npx.newaxis, npx.newaxis, :]), axis=2)
        #vs.kbot = update(vs.kbot, at[2:-2, 2:-2], npx.where(topo_z < 0.0, depth_levels, 0))
        vs.kbot = update(vs.kbot, at[...], npx.where(topo_z < 0.0, depth_levels, 0))
        vs.kbot = npx.where(vs.kbot < settings.nz, vs.kbot, 0)

    @veros_routine
    def set_initial_conditions(self, state):
        vs = state.variables
        settings = state.settings
        # initial conditions

        vs.temp = update(vs.temp, at[...], ((1 - vs.zt[None, None, :] / vs.zw[0]) * 15 * vs.maskT)[..., None])
        vs.salt = update(vs.salt, at[...], 35.0 * vs.maskT[..., None])

        # wind stress forcing
        latitudes = npx.array([-70, -45, -15, 0, 15, 45, 70])  # latitude points
        taux_values = npx.array([0, 0.2, -0.1, -0.02, -0.1, 0.1, 0.0])  # corresponding wind stress values (Pa)
        
        derivatives = npx.zeros_like(taux_values)  # Zero derivatives at all nodes
        hermite_interp = CubicHermiteSpline(latitudes, taux_values, derivatives)

        taux_interp = allocate(state.dimensions, ("yt",))
        taux_interp = hermite_interp(vs.yt)
        taux_interp = npx.where(vs.yt < -26, taux_interp * 2 , taux_interp)


        vs.surface_taux = taux_interp * vs.maskU[:, :, -1]


        ## Values extracted from IAPv4 (Cheng et al 2020, 2024) dataset averaged over year 2010 and 2019

        zonal_mean_sss = npx.array([34.67001704, 34.63708804, 34.59284335, 34.6202206 , 34.54753945, 34.56479844, 34.61101384, 34.61359597, 34.61194096, 34.59274873,
            34.57398229, 34.55517996, 34.52272882, 34.49713288, 34.45689823, 34.41201328, 34.36218568, 34.31692821, 34.28994908, 34.26151749,
            34.25168241, 34.2158881 , 34.16372239, 34.12272119, 34.09171997, 34.09845157, 34.1712854 , 34.24426871, 34.29039499, 34.37081634,
            34.48260338, 34.62309501, 34.75620075, 34.88317508, 35.05440028, 35.1867386 , 35.33791869, 35.4279112 , 35.46662819, 35.49371695,
            35.67063206, 35.76142323, 35.82876207, 35.88486441, 35.94132154, 35.98298257, 36.03538001, 36.10094125, 36.1557721 , 36.22029416,
            36.2675354 , 36.33197707, 36.35735855, 36.38259932, 36.43060197, 36.45539675, 36.49072787, 36.49381062, 36.50800661, 36.50130147,
            36.47643191, 36.42004443, 36.3592339 , 36.29832001, 36.21404774, 36.14395432, 36.04511348, 35.97061058, 35.90479953, 35.85478442,
            35.80969696, 35.79259125, 35.56735666, 35.66480693, 35.50077593, 35.61468585, 35.54231943, 35.61932639, 35.60957404, 35.47831699,
            35.5924475 , 35.51798111, 35.74147183, 35.70244128, 35.85362833, 35.99711234, 36.1856909 , 36.29449195, 36.3749242 , 36.4754053 ,
            36.55481494, 36.64698289, 36.72653646, 36.7669923 , 36.89391384, 36.9639049 , 37.03235181, 37.07904614, 37.07017125, 37.05302604,
            37.03224527, 37.01997213, 36.97463654, 36.91569158, 36.82846795, 36.80357655, 36.77139521, 36.70769852, 36.66941369, 36.60535292,
            36.61991013, 36.55693146, 36.41662378, 36.31415041, 36.19348845, 35.86371167, 35.67775623, 35.47436875, 35.09103384, 35.02624269,
            35.08368046, 34.64348574, 34.65819395, 34.97876273, 34.76664073, 34.94891149, 34.95712727, 34.92653744, 34.88415364, 33.9302836 ,
            34.42590542, 34.61132895, 34.9126867 , 35.15322618, 35.17445256, 35.1113819 , 35.15897676, 35.10391113, 35.08605015, 34.99299146,
            34.93260561, 34.92202096, 34.79224882, 34.78789948, 34.94418284, 34.65610723, 34.8367817 , 34.84809932, 34.8765537 , 34.95313342])       

        zonal_mean_sst = npx.array([-1.6929072 , -1.7039945 , -1.6887736 , -1.7273661 , -1.671726  , -1.6307597 , -1.5232211 , -1.4012039 , -1.2983394 , -1.2246363 ,
            -1.112023  , -1.0450966 , -0.93412673, -0.792174  , -0.56818783, -0.25099418,  0.14039113,  0.6683875 ,  1.225307  ,  1.6610435 ,
             1.9051646 ,  2.3402908 ,  2.819143  ,  3.3646622 ,  4.1040053 ,  4.8943048 ,  6.1276712 ,  7.1594625 ,  8.157542  ,  9.0477915 ,
            10.026489  , 11.226168  , 12.39084   , 13.381484  , 14.372064  , 15.334796  , 16.21714   , 16.968199  , 17.64556   , 18.267384  ,
            18.748999  , 19.286238  , 19.791107  , 20.241114  , 20.724735  , 21.086674  , 21.52012   , 21.988777  , 22.2746    , 22.505157  ,
            22.69231   , 22.915865  , 22.986622  , 23.106663  , 23.27416   , 23.303556  , 23.468405  , 23.538412  , 23.742863  , 24.02231   ,
            24.335629  , 24.672176  , 25.030067  , 25.415432  , 25.70537   , 25.983946  , 26.22694   , 26.43522   , 26.56902   , 26.619946  ,
            26.684847  , 26.708406  , 26.89783   , 26.943079  , 27.08407   , 27.383207  , 27.750195  , 28.043188  , 28.165499  , 28.12834   ,
            28.16315   , 28.02315   , 27.905241  , 27.741665  , 27.514143  , 27.45594   , 27.308008  , 27.179539  , 27.083462  , 26.90799   ,
            26.805136  , 26.686165  , 26.554756  , 26.33835   , 26.22309   , 26.066442  , 25.99069   , 25.71401   , 25.65439   , 25.415823  ,
            25.19774   , 24.880177  , 24.565958  , 24.141216  , 23.816343  , 23.46683   , 23.10876   , 22.7616    , 22.399986  , 22.0538    ,
            21.458164  , 21.053295  , 20.770044  , 20.240923  , 19.534222  , 18.292517  , 17.065329  , 15.513043  , 14.2864685 , 13.80079   ,
            13.277136  , 12.02754   , 11.5979    , 11.307836  , 10.717788  , 10.646079  , 10.01239   ,  9.097683  ,  8.812573  ,  8.587607  ,
             9.041585  ,  8.884177  ,  8.649707  ,  8.500429  ,  8.248819  ,  7.9172006 ,  8.169654  ,  7.9468327 ,  7.656074  ,  6.8750286 ,
             6.2949677 ,  5.7193856 ,  5.04115   ,  4.789436  ,  4.8636827 ,  4.123618  ,  3.999448  ,  3.415895  ,  2.8696399 ,  2.6441653 ])
        
        lat = npx.array([-74.5, -73.5, -72.5, -71.5, -70.5, -69.5, -68.5, -67.5, -66.5, -65.5, -64.5, -63.5, -62.5, -61.5, -60.5, -59.5, -58.5, -57.5,
            -56.5, -55.5, -54.5, -53.5, -52.5, -51.5, -50.5, -49.5, -48.5, -47.5, -46.5, -45.5, -44.5, -43.5, -42.5, -41.5, -40.5, -39.5,
            -38.5, -37.5, -36.5, -35.5, -34.5, -33.5, -32.5, -31.5, -30.5, -29.5, -28.5, -27.5, -26.5, -25.5, -24.5, -23.5, -22.5, -21.5,
            -20.5, -19.5, -18.5, -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5,  -9.5,  -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,
             -2.5,  -1.5,  -0.5,   0.5,   1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,   9.5,  10.5,  11.5,  12.5,  13.5,  14.5,
             15.5,  16.5,  17.5,  18.5,  19.5,  20.5,  21.5,  22.5,  23.5,  24.5,  25.5,  26.5,  27.5,  28.5,  29.5,  30.5,  31.5,  32.5,
             33.5,  34.5,  35.5,  36.5,  37.5,  38.5,  39.5,  40.5,  41.5,  42.5,  43.5,  44.5,  45.5,  46.5,  47.5,  48.5,  49.5,  50.5,
             51.5,  52.5,  53.5,  54.5,  55.5,  56.5,  57.5,  58.5,  59.5,  60.5,  61.5,  62.5,  63.5,  64.5,  65.5,  66.5,  67.5,  68.5,
             69.5,  70.5,  71.5,  72.5,  73.5,  74.5])
        
        # Fit a smooth spline
        tck_salinity = splrep(lat, zonal_mean_sss, s=3.)
        tck_temperature = splrep(lat, zonal_mean_sst, s=1.75)

        vs.t_star = splev(vs.yt, tck_temperature)
        vs.t_rest = vs.dzt[-1] / (10.0 * 86400.0) * vs.maskT[:, :, -1]
        vs.s_star = splev(vs.yt, tck_salinity)
        vs.s_rest = vs.dzt[-1] / (10.0 * 86400.0) * vs.maskT[:, :, -1]


        if settings.enable_tke:
            vs.forc_tke_surface = update(
                vs.forc_tke_surface,
                at[2:-2, 2:-2],
                npx.sqrt(
                    (0.5 * (vs.surface_taux[2:-2, 2:-2] + vs.surface_taux[1:-3, 2:-2]) / settings.rho_0) ** 2
                    + (0.5 * (vs.surface_tauy[2:-2, 2:-2] + vs.surface_tauy[2:-2, 1:-3]) / settings.rho_0) ** 2
                )
                ** (1.5),
            )

        if settings.enable_idemix:
            vs.forc_iw_bottom = 1e-6 * vs.maskW[:, :, -1]
            vs.forc_iw_surface = 1e-7 * vs.maskW[:, :, -1]

    @veros_routine
    def set_forcing(self, state):
        vs = state.variables
        vs.forc_temp_surface = vs.t_rest * (vs.t_star - vs.temp[:, :, -1, vs.tau])
        vs.forc_salt_surface = vs.s_rest * (vs.s_star - vs.salt[:, :, -1, vs.tau])

    @veros_routine
    def set_diagnostics(self, state):

        settings = state.settings
        #state.diagnostics["snapshot"].output_variables += ["t_star",]
        state.diagnostics["snapshot"].output_frequency = 86400.0 * 365  # Every year
        state.diagnostics["averages"].output_variables = (
            "salt",
            "temp",
            "u",
            "v",
            "w",
            "psi",
            "rho",
            "forc_salt_surface",
            "forc_temp_surface",
            "t_star",
            "s_star",
        )

        state.diagnostics["averages"].output_frequency = 86400.0 * 365 / 12
        state.diagnostics["averages"].sampling_frequency = settings.dt_tracer * 10
        state.diagnostics["overturning"].output_frequency = 86400.0 * 365 / 12
        state.diagnostics["overturning"].sampling_frequency = settings.dt_tracer * 10
        state.diagnostics["tracer_monitor"].output_frequency = 86400.0 * 365 / 12
        state.diagnostics["energy"].output_frequency = 86400.0 * 365 / 12
        state.diagnostics["energy"].sampling_frequency = settings.dt_tracer * 10

    @veros_routine
    def after_timestep(self, state):
        pass


    @staticmethod
    def mi96_1d2(dz_min, dz_bot, h4, h3, K):
        '''
        Calculate depth levels for a given set of input parameters using Madec & Imbard (1996) function.

        Parameters:
        - dz_min:   Value of e3 at the connection point [meters]
        - dz_bot :  Value of e3 at the bottom 
        - h4:     Position of the inflexion point
        - h3:     Slope of the tanh function
        - K:        Number of vertical levels

        Returns:
        - depth:    Depth of the levels
        '''

        depth = npx.zeros((2, K ))
        alpha =  npx.tanh((3/2 - h4)/h3)
        beta = npx.tanh((K-1/2-h4)/h3)
        gamma = h3 * npx.log(npx.cosh((1-h4)/h3))

        h0 = (gamma - alpha)/(alpha - beta) * (dz_bot - dz_min) - dz_min
        h1 = (alpha * dz_bot - beta* dz_min) / (beta - alpha)
        h2 = (dz_bot - dz_min)/ (alpha - beta)
        h0,h1,h2 = -h0,-h1,-h2

        # Calculate depth at T and W-points
        for jk in range(1, K+1):
            zw = float(jk)
            zt = float(jk) + 0.5

            depth = update(depth, at[0, jk-1], h0 -h1*zw - h2 * h3 * npx.log(npx.cosh((zw - h4) / h3)))
            depth = update(depth, at[1, jk-1], h0 -h1*zt - h2 * h3 * npx.log(npx.cosh((zt - h4) / h3)))

        return depth

    
    @staticmethod
    def smooth_step(lam, lam_left, lam_right):
        '''
        Parameters:
        - lam:          coordinate value (e.g. lon or lat)
        - lam_left:     lower end of smoothing function
        - lam_right:    upper end of smoothing function

        Returns:
        - step:         1d array of the step function
        '''
        step = npx.zeros_like(lam)
        in_range = (lam >= lam_left) & (lam <= lam_right)
        x = (lam[in_range] - lam_left) / (lam_right - lam_left)
        step = update( step, at[in_range], 6 * x**5 - 15 * x**4 + 10 * x**3)
        step = update( step, at[lam > lam_right], 1.0)
        return step

    @staticmethod
    def exp_bathymetry(lam, lam_left, lam_right, width, slope, dist_taper,self):
        '''
        Compute tapered exponential slopes to define the bathymetry.

        Parameters:
        - lam:          coordinate value (e.g. lon or lat) 
        - lam_left:     lower end of lam
        - lam_right:    upper end of lam
        - width:        width of the basin in degrees longitude
        - slope:        slope of the exponential in degrees longitude
        - dist_taper:   distance from boundary where Hmax should be reached

        Returns:
        -exp:           value of the exponential function at `lam`
        '''
        exp = npx.zeros_like(lam)

        norm = 1 + npx.exp(-width / slope)

        left_taper = (lam >= lam_left) & (lam <= lam_left + dist_taper)
        step_left = self.smooth_step(lam[left_taper], lam_left, lam_left + dist_taper)
        exp = update(exp, at[left_taper], (1 - (npx.exp(-(lam[left_taper] - lam_left) / slope)) / norm) * (1 - step_left) + step_left)

        right_taper = (lam >= lam_right - dist_taper) & (lam <= lam_right)
        step_right = 1 - self.smooth_step(lam[right_taper], lam_right - dist_taper, lam_right)
        exp = update(exp, at[right_taper], (1 - (npx.exp((lam[right_taper] - lam_right) / slope)) / norm) * (1 - step_right) + step_right)

        main_basin = (lam > lam_left + dist_taper) & (lam < lam_right - dist_taper)
        exp = update(exp, at[main_basin], 1.0)

        return exp
    
    @staticmethod
    def get_bathymetry(self,state, lon_mesh_t, lat_mesh_t, H_min):
        '''
        Compute bathymetry as 2D numpy array.
        '''
        lat_channel_min = -65.     # Minimum channel latitude on T-point (approx.)     
        lat_channel_max = -45.     # Maximum channel latitude on T-point (approx.)
        slope = 3.                 # slope
        H_max = 4000.              # Maximum depth of the bathymetry on W-point
        #H_min = 2000.              # Minimum depth of the bathymetry on W-point (approx.)
        width           = abs(self.lon_max - self.lon_min)
        channel_width   = abs(lat_channel_max - lat_channel_min)

        zy_cha = self.exp_bathymetry(lat_mesh_t, lat_channel_min, lat_channel_max, width, slope, channel_width / 2, self)

        zx_raw = self.exp_bathymetry(lon_mesh_t, self.lon_min, self.lon_max, width, slope, channel_width / 2, self) # /!\ I chose long_max-1 for a better symmetry, not anymore because not the same grid 
        zx = zx_raw * (1.0 - zy_cha) + zy_cha

        slope_lat = npx.cos( state.settings.pi * self.lat_max /180) * slope
        zy = self.exp_bathymetry(lat_mesh_t, self.lat_min, self.lat_max, width, slope_lat, channel_width / 2, self)

        pbathy = zx * zy * (H_max - H_min) + H_min

        return pbathy
    
    @staticmethod
    def add_gauss_ring(self, state, lon_mesh_t, lat_mesh_t):
        """
        Add a ring of Gaussian bumps to the bathymetry representing an idealized drake-sill.

        Returns:
        float: Resulting updated bathymetry [meters]
        """
        vs = state.variables
        lat_channel_min = -65.     # Minimum channel latitude on T-point (approx.)     
        lat_channel_max = -45.     # Maximum channel latitude on T-point (approx.)
        #drake_si   
        slope_ds = 4.              # Length scale of the slope of the sill [degrees]
        depth_ds = 2500.           # Depth of the sill [meters]


        lat_0       = (lat_channel_max + lat_channel_min) / 2
        lon_0       = vs.xt.min()
        radius      = abs(lat_channel_max - lat_channel_min) / 2

        # taper the gaussian ring eastward 
        taper       = self.smooth_step(lon_mesh_t, lon_0, lon_0 + slope_ds)
        # shift grid
        zx = lon_mesh_t - lon_0
        zy = lat_mesh_t - lat_0

        # Calculate the exponent part of the Gaussian function
        exp_arg = (- zx**2 - zy**2 + 2 * radius * npx.sqrt(zx**2 + zy**2) - radius**2) / slope_ds**2

        # Calculate the resulting bathymetry depth
        gauss_ring = npx.where(vs.bathymetry >= depth_ds,
                            (depth_ds - vs.bathymetry) * npx.exp(exp_arg) + vs.bathymetry,
                            vs.bathymetry)
        
        # update bathymetry
        new_bathymetry = taper * gauss_ring + (1. - taper) * vs.bathymetry
        return(new_bathymetry)